name: prox4d
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.5
  - pip
  - numpy==1.19.2
  - scipy==1.5.2
  - matplotlib==3.4.2
  - jupyter==1.0.0
  - pip:
    - segyio==1.9.6
    - git+https://github.com/DIG-Kaust/pysubsurface
    - git+https://github.com/pylops/pylops@dev
    - git+https://github.com/pylops/pyproximal@dev
    - numba
    - pyvista
    - lasio
    - segyio
    - matplotlib-scalebar
    - shapely
    - descartes
    - pyyaml
    - Deprecated
    - git+https://github.com/cjohnson318/geostatsmodels.git

